todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="catalog")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_list/urls.py
from django.urls import path

from .views import (
    HomePage,
    ToggleAssignToTaskView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
)

urlpatterns = [
    path("", HomePage.as_view(), name="home-page"),
    path(
        "<int:pk>/toggle-assign/",
        ToggleAssignToTaskView.as_view(),
        name="toggle-task-assign"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list",
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create",
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete",
    ),
]

app_name = "catalog"

todo_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Task(models.Model):
    content = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False, null=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["-is_completed", "-created"]

    def __str__(self):
        return (
            f"Content: {self.content}\n"
            f"Created {self.created}\n"
            f"Tags: {', '.join(str(tag) for tag in self.tags.all())}"
        )

todo_list/forms.py
from django import forms
from todo_list.models import Task, Tag


class TaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        # Check if there are any tags in the database, if not, display a message.
        if not Tag.objects.exists():
            self.fields['tags'].queryset = Tag.objects.none()
            self.fields['tags'].help_text = 'No tags available. Please create a tag first.'

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
        error_messages={'required': 'Please select at least one tag.'}
    )

    class Meta:
        model = Task
        fields = "__all__"
        error_messages = {
            'title': {'required': 'Please enter a title.'},
            'description': {'required': 'Please enter a description.'},
            # Add error messages for other fields as needed
        }

todo_list/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic, View

from .forms import TaskForm
from .models import Tag, Task


class HomePage(generic.ListView):
    model = Task
    template_name = "todo/home_page.html"


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("catalog:home-page")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("catalog:home-page")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "todo/task_confirm_delete.html"
    success_url = reverse_lazy("catalog:home-page")


class TagListView(generic.ListView):
    model = Tag
    template_name = "todo/tags_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    template_name = "todo/tag_form.html"
    success_url = reverse_lazy("catalog:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    template_name = "todo/tag_form.html"
    success_url = reverse_lazy("catalog:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "todo/tag_confirm_delete.html"
    success_url = reverse_lazy("catalog:tag-list")


class ToggleAssignToTaskView(View):
    def post(self, request, pk):
        task = get_object_or_404(Task, id=pk)

        task.is_completed = not task.is_completed
        task.save()

        return redirect(reverse_lazy(
            "catalog:home-page"
        ))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Todo List</title>{% endblock %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">

        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}

      </div>
      <div class="col-sm-10 ">

        {% block content %}{% endblock %}

      </div>
    </div>
  </div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'catalog:home-page' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:tag-list' %}">Tags</a></li>
</ul>

templates/todo/home_page.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'catalog:task-create' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </h1>

  {% for task in task_list %}
    <hr>
    <h5>
      <strong>{{ task.content }}</strong>
      {% if task.is_completed %}
        <span style="color: green">Done</span>
        <form method="post" action="{% url 'catalog:toggle-task-assign' pk=task.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary link-to-page">
            Undo
          </button>
        </form>
      {% else %}
        <span style="color: red">Not done</span>
        <form method="post" action="{% url 'catalog:toggle-task-assign' pk=task.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-success link-to-page">
            Complete
          </button>
        </form>
      {% endif %}
    </h5>
    <p>
    {% if task.is_completed %}
      Created: {{ task.created }}
    {% else %}
      Created: {{ task.created }},
      <span style="color: red">Deadline: {{ task.deadline }}</span>
    {% endif %}
    </p>
    <p>
      Tags:
      {% for tag in task.tags.all %}
         {{ tag.name }}
      {% endfor %}
      <a href="{% url 'catalog:task-update' pk=task.id %}" class="text">
        Update
      </a>
      <a href="{% url 'catalog:task-delete' pk=task.id %}" class="text">
        Delete
      </a>
    </p>

  {% empty %}
    <p>No tasks!</p>
  {% endfor %}

{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tags_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a href="{% url 'catalog:tag-create' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'catalog:tag-update' pk=tag.id %}" class="btn btn-secondary">
              Update
            </a>
          </td>
          <td>
            <a href="{% url 'catalog:tag-delete' pk=tag.id %}" class="btn btn-secondary">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags in the service.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}